steps:
- download: current
  artifact: nuget
- bash: |
    set -e
    export PATH="$PATH:/$HOME/.dotnet/tools"

    mkdir test-$(command)/
    cd test-$(command)

    echo "<configuration><packageSources><add key='local' value='$(Pipeline.Workspace)/nuget' /></packageSources></configuration>" > NuGet.config
    version=$(cat $(Pipeline.Workspace)/nuget/version.txt)

    # Install the dotnet-$(command) tool
    dotnet tool install --global dotnet-$(command) --version $version --add-source $(Pipeline.Workspace)/nuget

    # Create a new console application
    dotnet new console

    # Install and use dotnet $(command)
    dotnet $(command) install
    dotnet $(command) -o $(Build.ArtifactStagingDirectory)/packages/$(container)
  workingDirectory: $(Pipeline.Workspace)
  displayName: Run dotnet $(command)
- publish: $(Build.ArtifactStagingDirectory)/packages/
  artifact: packages