image: Visual Studio 2017

version: '0.1.{build}'

before_build:
  - dotnet restore dotnet-packaging.sln

build_script:
  - dotnet pack dotnet-packaging.sln -c Release --version-suffix r%APPVEYOR_BUILD_NUMBER%

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\Packaging.Targets.Tests\
  - cmd: dotnet restore
  - cmd: dotnet build
  - cmd: dotnet vstest bin\Debug\netcoreapp2.0\Packaging.Targets.Tests.dll /logger:trx;LogFileName=testresults.trx
  - ps: '& (Join-Path $env:APPVEYOR_BUILD_FOLDER "appveyor-testresults.ps1")'
  - cmd: cd ..

artifacts:
  - path: dotnet-tarball\bin\Release\dotnet-tarball.0.1.1-r$(APPVEYOR_BUILD_NUMBER).nupkg
  - path: dotnet-zip\bin\Release\dotnet-zip.0.1.1-r$(APPVEYOR_BUILD_NUMBER).nupkg
  - path: dotnet-rpm\bin\Release\dotnet-rpm.0.1.1-r$(APPVEYOR_BUILD_NUMBER).nupkg
  - path: dotnet-deb\bin\Release\dotnet-deb.0.1.1-r$(APPVEYOR_BUILD_NUMBER).nupkg
  - path: Packaging.Targets\bin\Release\Packaging.Targets.0.1.1-r$(APPVEYOR_BUILD_NUMBER).nupkg

deploy:
  provider: NuGet
  on:
    branch: master
  api_key:
    secure: PWTSvjALUGYuMrcnQX7RZxDW/M8WtIXfihQUek4xMjN2bQj73gudiusqIOVUEwdo
  skip_symbols: true
